name: aqi-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit==1.41.1
      - streamlit-aggrid==1.1.9
      - streamlit-option-menu==0.4.0
      - pandas==2.2.3
      - numpy==2.2.1
      - matplotlib==3.10.0
      - seaborn==0.13.2
      - plotly==5.24.1
      - altair==5.5.0
      - affine==2.4.0
      - statsmodels==0.14.5
      - scikit-learn==1.6.0
      - scikit-posthocs==0.11.4   
      - scipy==1.16.2         
