name: aqi-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pyproj
  - rtree
  - pip
  - pip:
      - streamlit==1.41.1
      - pandas==2.2.3
      - matplotlib==3.10.0
      - seaborn==0.13.2
      - plotly==5.24.1
      - statsmodels==0.14.5
      - numpy==2.2.1
      - scikit-learn==1.6.0
      - streamlit-aggrid==1.1.9
      - streamlit-option-menu==0.4.0
      - affine==2.4.0
      - altair==5.5.0
