name: aqi-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - geopandas
  - contextily
  - shapely
  - fiona
  - pyproj
  - rtree
  - gdal
  - pip
  - pip:
      - streamlit==1.41.1
      - pandas==2.2.3
      - matplotlib==3.10.0
      - seaborn==0.13.2
      - plotly==5.24.1
      - statsmodels==0.14.4
      - numpy==2.2.1
      - scikit-learn==1.6.0
